version: "3"
services:
  postgres:
    image: postgres:14
    container_name: movies_db
    env_file: '.env'
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    command: python src/manage.py runserver 0.0.0.0:8000
    image: movies_t
    container_name: movies_app
    env_file: .env
    depends_on: 
      - postgres
    ports:
      - 8000:8000
    volumes:
      - .:/app/

volumes:
  pg_data: