version: "3"
services:
  postgres:
    image: postgres:14
    container_name: movies_db
    env_file: '.env'
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    command: "gunicorn src.config.wsgi -c gunicorn_config.py"
    image: movies_t
    container_name: movies_app
    env_file: .env
    depends_on: 
      - postgres
    ports:
      - 8000:8000
    volumes:
      - .:/app/

  nginx:
    image: nginx:1.23.3
    container_name: support_nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./staticfiles:/usr/share/nginx/html/static
    depends_on:
      - app

volumes:
  pg_data: