# Generated by Django 4.1.13 on 2024-02-27 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="tittle",
            new_name="title",
        ),
    ]
